export const FETCH_WAGE_DATA = 'FETCH_WAGE_DATA'
export const FETCH_TIME_DATA = 'FETCH_TIME_DATA'
export const TOGGLE_INFO_MODAL = 'TOGGLE_INFO_MODAL'
export const TOGGLE_ACTIVE_TAB = 'TOGGLE_ACTIVE_TAB'